blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('<int:pk>/', views.DetailView.as_view(), name='detail'),
  path('<int:blog_id>/post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='landing.html'), name='landing')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
  owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
  name = models.CharField(max_length=200)
  notes = models.TextField(blank=True, null=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return f'({self.id}) {self.name}'

class Post(models.Model):
  author = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
  blog = models.ForeignKey(Blog, on_delete=models.SET_NULL, blank=True, null=True)
  title = models.CharField(max_length=200)
  content = models.TextField()
  notes = models.TextField(blank=True, null=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return f'({self.id}) {self.title}'

class Comment(models.Model):
  owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
  post = models.ForeignKey(Post, on_delete=models.SET_NULL, blank=True, null=True)
  parent_comment = models.ForeignKey("Comment", on_delete=models.SET_NULL, blank=True, null=True)
  content = models.TextField()
  notes = models.TextField(blank=True, null=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  
  def __str__(self):
    return f'({self.id}) {self.content}'

blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Blog, Post, Comment

class IndexView(generic.ListView):
  template_name = 'blog/index.html'
  context_object_name = 'blog_list'

  def get_queryset(self):
    return Blog.objects.order_by('-created_at')

class DetailView(generic.DetailView):
  model = Blog
  template_name = 'blog/detail.html'

class PostDetailView(generic.DetailView):
  model = Post
  template_name = 'post/detail.html'

blog/templates/blog/detail.html
{% extends 'app_base.html' %}
{% load static %}
{% block content %}
  <!-- Header -->
  <header class="blog bg-primary text-white text-center">
    <div class="container">
      <h1 class="text-uppercase mb-0">{{ blog }}<br /><small class="text-muted">just a test</small></h1>
      <hr class="star-light">
    </div>
  </header>

  <div class="container" style="padding-top: 30px">
    <div class="row">
      <div class="col">
      </div>
      <div class="col-md-auto">
        {% for post in blog.post_set.all %}
          <a href="{% url 'blog:post_detail' blog.id post.id %}">
            {{ post }}
          </a>
        {% endfor %}
      </div>
      <div class="col">
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'app_base.html' %}
{% block content %}
  <!-- Header -->
  <header class="blog bg-primary text-white text-center">
    <div class="container">
      <h1 class="text-uppercase mb-0">ad infinitum<br /><small class="text-muted">trent's blog list</small></h1>
      <hr class="star-light">
    </div>
  </header>

  <div class="container" style="padding-top: 30px">
    <div class="row">
      <div class="col">
      </div>
      <div class="col-md-auto">
        {% if blog_list %}
          {% for blog in blog_list %}
            <a href="{% url 'blog:detail' blog.id %}">
              <blockquote class="blockquote text-right">
                <p class="mb-0">{{ blog }}</p>
                <footer class="blockquote-footer">{{ blog.owner }}</footer>
              </blockquote>
            </a>
          {% endfor %}
        {% else %}
        <p>no blogs are available.</p>
        {% endif %}
      </div>
      <div class="col">
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/post/detail.html
{% extends 'app_base.html' %}
{% load static %}
{% block content %}
  <!-- Header -->
  <header class="blog bg-primary text-white text-center">
    <div class="container">
      <h1 class="text-uppercase mb-0">{{ post }}<br /><small class="text-muted">by: {{ post.author }}</small></h1>
      <hr class="star-light">
    </div>
  </header>

  <div class="container" style="padding-top: 30px">
    <div class="row">
      <div class="col"></div>
      <div class="col-md-auto">
        {{ post.content }}
      </div>
      <div class="col"></div>
    </div>
    <hr />
    <h3>Comments</h3>
    {% for comment in post.comment_set.all %}
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{ comment.owner }}</h5>
          <h6 class="card-subtitle mb-2 text-muted"><small>{{ comment.created_at }}</small></h6>
          <p class="card-text">{{ comment }}</p>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}